spring.datasource.url=jdbc:postgresql:/HogwartsAPI-env.eba-gm2q2cpe.us-east-1.elasticbeanstalk.com/hogwarts
spring.datasource.username=postgres
spring.datasource.password=mausot
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
springdoc.swagger-ui.path=/documentacion
springdoc.swagger-ui.operationsSorter=method

