spring.datasource.url=jdbc:postgresql://hogwarts-db.csgga3znfxrd.us-east-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=mausot
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
springdoc.swagger-ui.path=/documentacion
springdoc.swagger-ui.operationsSorter=method